--- clthreads-2.4.2/source/Makefile.orig	2018-08-24 20:40:37.000000000 +0200
+++ clthreads-2.4.2/source/Makefile	2021-09-26 21:55:07.580681263 +0200
@@ -32,8 +32,7 @@ VERSION = $(MAJVERS).$(MINVERS)
 
 
 CPPFLAGS += -DVERSION=\"$(VERSION)\" -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -I.  
-CXXFLAGS += -Wall -O2 -fPIC
-CXXFLAGS += -march=native
+CXXFLAGS += -Wall -fPIC
 LDLFAGS += 
 LDLIBS +=
 
@@ -51,11 +50,11 @@ $(CLTHREADS_MIN): $(CLTHREADS_O)
 
 
 install:	$(CLTHREADS_MIN)
-	install -d $(DESTDIR)$(PREFIX)/$(INCDIR)
-	install -d $(DESTDIR)$(PREFIX)/$(LIBDIR)
+	install -d $(DESTDIR)$(INCDIR)
+	install -d $(DESTDIR)$(LIBDIR)
 	install -m 644 $(CLTHREADS_H) $(DESTDIR)$(INCDIR)
 	install -m 755 $(CLTHREADS_MIN) $(DESTDIR)$(LIBDIR)
-	ldconfig
+	-/sbin/ldconfig -n -N $(DESTDIR)$(LIBDIR)
 	ln -sf $(CLTHREADS_MIN) $(DESTDIR)$(LIBDIR)/$(CLTHREADS_SO)
 
 uninstall:
